### ISSUE TITLE
Bookings made from the app aren't visible anywhere else

### ISSUE THREAD

**Issue by garo** [futurice/meeting-room-tablet#30]
For some reason the bookings made from the application are not visible in anywhere else (not in other app instances and not in browser based google calendar). Tested with Android 5.1.1 and 4.2.2.

Also deleting an event booked from the application doesn't seem to clear the event from the app calendar.

Events made from Google calendar via browser are visible in the app just fine.

**Comment by Wisheri** [comment]
Does the account used with the tablet have the correct rights to book rooms? Can you also check that is the calendar sync running correctly in the tablet?

**Comment by martinsettle** [comment]
I'm having this same issue. I can use the account on the tablet to book a room through the web browser, which will then sync and display in the app. Any bookings made on the app, however, do not sync back to google calendar. The account used on the tablet is set up as a super-admin in Google Apps, and I've tried it with the "Require address book contacts for reserving" both off and on.

**Comment by Wisheri** [comment]
Thanks for reporting! I'll have a look at it.

**Comment by delize** [comment]
Just wanted to chime in, I am having the same problem. My company was actually going to use this going forward instead of Pronestor and Eventboard, but this is a pretty big show stopper.

It was working yesterday (which coincidentally was the first time I found the app and configured it), and then from there, left it on overnight, and then the application stopped working.

**Comment by martinsettle** [comment]
Oh, sorry... I figured this out. It had to do with how the tablet accounts with Google Apps were given permissions on the calendar for the resource. Somewhere in the documentation it said they had to have the ability to "See All Event Details", but they actually need to have "Make changes to events". Once I changed that permission it allowed the data to synchronize back into Google Calendar.

**Comment by delize** [comment]
This is still a bug though. The app should be able to book room resources, even if they are set to show busy/free details.

In situations why this doesn't work, think of a board room. We don't want to broad cast meetings that pertain only to our CEO/CTO/CSO to the entire company, especially for use with this application.

Alternatively, if the only way to make this work is to see all event details, there NEEDS to be a way to have it just show "free/busy" details rather than showing the actual events themselves.

**Comment by delize** [comment]
Just as a heads up, the company I work for will be trying to remedy this. 

This application works great for our use case, except for this problem. And spending $16K on a platform, or fixing the code ourselves and spending ~$1K for tablets makes a lot more sense.

**Comment by delize** [comment]
Here is the debug code:

```
03-11 17:02:57.025  31593-32550/? E/EventHandler﹕ Can't insert event into thousandeyes.com_37323839323333392d323838@resource.calendar.google.com: Forbidden
    com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
    {
    "errors": [
    {
    "reason": "forbidden",
    "domain": "global",
    "message": "Forbidden"
    }
    ],
    "message": "Forbidden",
    "code": 403
    }
            at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
            at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
            at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
            at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
            at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
            at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
            at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
            at com.google.android.syncadapters.calendar.Utils.executeAndLog(Utils.java:493)
            at com.google.android.syncadapters.calendar.EventHandler.sendEntityToServer(EventHandler.java:424)
            at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.sendEntityToServer(CalendarSyncAdapterApiary.java:3943)
            at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.processLocalChanges(CalendarSyncAdapterApiary.java:3857)
            at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.processLocalChangesForHandler(CalendarSyncAdapterApiary.java:3755)
            at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.performSync(CalendarSyncAdapterApiary.java:779)
            at com.google.android.syncadapters.calendar.CalendarSyncAdapterApiary.onPerformLoggedSync(CalendarSyncAdapterApiary.java:548)
            at com.android.emailcommon.syncadapter.LoggingThreadedSyncAdapter.onPerformSync(LoggingThreadedSyncAdapter.java:49)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```
